### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by mack-anderson** [DawsonMacPhee/FantasyHockeySelector#9]
Determine placement of player selection, player selection interface, and the player stats  menu then create the landing page.

**Comment by DawsonMacPhee** [comment]
@mack-anderson - The linking between pages needs to be slightly different. Right now you're linking to different html pages... instead you should be linking via endpoints to springboot. Springboot MVC sets up html pages in the resources folder for you, so instead of linking to stats.html, you should link to the endpoint /stats (or /html_name_without_extension)

**Comment by DawsonMacPhee** [comment]
This way, the url doesn't contain a ".html" at the end... it will only have www.url/stats
